### ISSUE TITLE
Project is dead, just like NESHLA

### ISSUE THREAD

**Issue by darkhog** [wiz-lang/wiz#13]
Shame, as such high level assembly would be really great to make some cool nes games.

**Comment by CREEATION** [comment]
or is it?

**Comment by darkhog** [comment]
Yeah. Rewrite? Why rewrite? D is a good language, everyone needs some D in their lives. And by rewriting you're essentially throwing the work you already done out of the window and have to do exact same thing over again.

My current game is being made in Unity. Somewhat midway of its development I've developed a hate towards Unity for their petty business practices (dark theme pro-only, c'mon!). Now I'd rather would have made the game in Godot or Unreal or some other engine. But I'm sticking with unity at least until the game is finished. Why? Because I don't enjoy doing the work I've already done again, just in a different programming language. I would have the exact same view even if it wasn't a game I would eventually sell (currently crowdfunding it on patreon). Obviously my next project would be in Godot, but that's about it.

**Comment by Bananattack** [comment]
Rewrites don't necessarily throw everything out the window. Sometimes a rewrite is necessary a project to grow, when it has hit a dead-end. Several ideas were learned from the D version of the compiler and carried ahead to this version. The language was considerably re-worked from the D release, so it made a lot of sense to just start the entire project from the ground up. Originally it was in fact, just a D to C++ port, but after that goal was met, it grew into its own thing. For me, this path made sense as a solo developer. I don't claim it's necessarily the best idea for everybody, but sometimes it's better to cut your losses and start over.

Anyway, current state of development is now up on Github.
