### ISSUE TITLE
65c02: wrong opcode for jmp (addr, X)

### ISSUE THREAD

**Issue by est77** [wiz-lang/wiz#138]
In src/wiz/platform/mos6502_platform.cpp:

builtins.createInstruction(InstructionSignature(BranchKind::Goto, 0, {patternAtLeast0, patternIndirectJumpIndexedByX}), encodingU16Operand, InstructionOptions({0x6C}, {1}, {}));

But 0x6c is the opcode for jmp (addr). The correct opcode for jmp (addr, X) is 0x7C according to 
http://www.6502.org/tutorials/65c02opcodes.html

**Comment by est77** [comment]
I think that the last commit reintroduced this bug:
https://github.com/wiz-lang/wiz/commit/4625c29ee4842b7d63e183149c37c69e024d479a#diff-7744eaa157ef71a64645b81480de1a5807f6639cda900e88790e9e3db1e7cd16R516

**Comment by Bananattack** [comment]
Whoops! I'll look into this one.

**Comment by est77** [comment]
Thanks!
