### ISSUE TITLE
Fix for .sfc files not loading in bsnes-plus

### ISSUE THREAD

**Issue by undisbeliever** [wiz-lang/wiz#40]
The SNES dev manual states the Game Title header (0xFFC0 - FFD4) should be space padded.

Adding a title (with padded spaces) to the SNES example will make `hello.sfc` to work on bsnes-plus.
``` diff
diff --git a/examples/snes/hello/banks.wiz b/examples/snes/hello/banks.wiz
index 3705b9d..fd7e2d6 100644
--- a/examples/snes/hello/banks.wiz
+++ b/examples/snes/hello/banks.wiz
@@ -1,9 +1,10 @@
 config {
     map_mode = "lorom",
     fastrom = true,
+    title = "HELLO WORLD          ",
 }
```

**Comment by Bananattack** [comment]
Good catch! I hadn't tested bsnes-plus, but I did test bsnes, snes9x and no$sns. Either way, the header spec should do the right thing here. Right now the `snes_format.cpp` code is zero-filling the entire SNES/SFC header, getting it to space-fill the title section instead should be an easy fix.
