### ISSUE TITLE
Wrong offset for mapmode and romtype entries in SNES headers

### ISSUE THREAD

**Issue by red-llama** [wiz-lang/wiz#91]
According to this:
https://snesdev.mesen.ca/wiki/index.php?title=Internal_ROM_Header

mapModeSetting should be written to offset 0xD5 and cartType to 0xD6.

I checked that after the changes bsnes detects the map type and expansion_type of the ROM correctly.
I didn't check other header entries.

**Comment by Bananattack** [comment]
Hi @red-llama, thank you for spotting this issue! I'll try to get to fixing this soon, and I'll try to double-check if there are any other mistakes with how the SNES headers get written.

**Comment by red-llama** [comment]
Thanks for the fix!
